export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_SIGNUP = 'AUTH_SIGNUP';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const SET_STORIES = 'SET_STORIES';
export const SET_USER_STORIES = 'SET_USER_STORIES';
export const SET_SEARCH_STORIES = 'SET_SEARCH_STORIES';
export const SET_TRENDING = 'SET_TRENDING';
export const STORY_SUCCESS = 'STORY_SUCCESS';
export const STORY_FAIL = 'STORY_FAIL';

export const SET_GALLERIES = 'SET_GALLERIES';
export const RESET_GALLERIES = 'RESET_GALLERIES';
export const REMOVE_GALLERY = 'REMOVE_GALLERY';
export const GALLERY_SUCCESS = 'GALLERY_SUCCESS';
export const GALLERY_FAIL = 'GALLERY_FAIL';

export const SET_USERS = 'SET_USERS';
export const SET_USER = 'SET_USER';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_ONLINE_USERS = 'SET_ONLINE_USERS';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_FAIL = 'USER_FAIL';

export const SET_PROFILE = 'SET_PROFILE';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAIL = 'PROFILE_FAIL';

export const SET_DASHBOARD = 'SET_DASHBOARD';
export const SET_LEADERBOARD = 'SET_LEADERBOARD';
export const DASHBOARD_SUCCESS = 'DASHBOARD_SUCCESS';
export const DASHBOARD_FAIL = 'DASHBOARD_FAIL';

export const SET_BOOKMARKS = 'SET_BOOKMARKS';
export const BOOKMARK_SUCCESS = 'BOOKMARK_SUCCESS';
export const BOOKMARK_FAIL = 'BOOKMARK_FAIL';

export const SET_REPORTS = 'SET_REPORTS';
export const REPORT_SUCCESS = 'REPORT_SUCCESS';
export const REPORT_FAIL = 'REPORT_FAIL';

export const SET_SETTINGS = 'SET_SETTINGS';
export const SETTING_SUCCESS = 'SETTING_SUCCESS';
export const SETTING_FAIL = 'SETTING_FAIL';